### ISSUE TITLE
backup: did not backup all files

### ISSUE THREAD

**Issue by gi8lino** [vshn/k8up#105]
When I try to create a PVC backup, the following error occurs:

```
Starting backup for folder nextcloud-claim0
done: 0.00% 
done: 63.95% 
error cannot open on file /data/nextcloud-claim0/config/config.php
backup finished! new files: 0 changed files: 0 bytes added: 356
Listing snapshots
snapshots command:
35 Snapshots
```

config.php stat:
```bash
-rw-r-----  1 www-data www-data 1.6K Aug  1 21:17 config.php
```

This permission error occurs in other containers too.

**Comment by Kidswiss** [comment]
Hi @gi8lino 

Can you please share your operator deployment manifest?

Also are you using plain k8s or OpenShift?

**Comment by gi8lino** [comment]
Hi
I use k3s.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: k8up
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8up
    app.kubernetes.io/version: v0.1.10
    helm.sh/chart: k8up-0.6.1
  name: k8up
  namespace: k8up
spec:
  template:
    spec:
      containers:
      - env:
        - name: BACKUP_IMAGE
          value: docker.io/vshn/wrestic:v0.1.8
        - name: BACKUP_GLOBALREPOPASSWORD
          value: banana
        - name: BACKUP_GLOBALACCESSKEYID
          value: foo
        - name: BACKUP_GLOBALSECRETACCESSKEY
          value: bar
        - name: BACKUP_GLOBALS3ENDPOINT
          value: https://minio-backup.foobar.com
        image: docker.io/vshn/k8up:v0.1.10
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: k8up-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 20m
            memory: 128Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: k8up
      serviceAccountName: k8up
```
