### ISSUE TITLE
Save snapshots into CRDs for better visibility

### ISSUE THREAD

**Issue by Kidswiss** [vshn/k8up#122]
Right now we need to use the restic CLI or the webhooks to get an actual list of the backups available.

To make the usability easier wrestic/k8up should manage the snapshots in CRDs. This increases the visibility and ease of use. I'd suggest to create one object per snapshot so a restore could reference the snapshot object from the k8s API.

**Comment by shreddedbacon** [comment]
Is this going to be added to the re-write? This would solve so many issues for us.

**Comment by tobru** [comment]
The features for the rewrite are tracked here: https://github.com/vshn/k8up/milestone/1. This one will be planned next, it's now added to the respective milestone.

**Comment by tobru** [comment]
@shreddedbacon Would you mind to add some use-cases to this issue? We would like to understand how this feature could be implemented and getting to know your use-cases would very much help. Thanks.

**Comment by shreddedbacon** [comment]
What would be helpful, instead of sending a gigantic webhook with all of the snapshots if the following was possible.

Storing all of the snapshots for a specific namespace, within that namespace.

One option to achieve this could be to create a new kind called `Snapshots`
Any time an individual snapshot is completed, append the information for that snapshot to the `Snapshots` object within the namespace it was run in.

You could have the spec like this
```
spec:
  bucketName: "example-bucket"
  snapshots:
    - id: "cb75d45c263487bda966eea844414edaab1a353c2a0996289cbf13572e22c61f"
      time: "2020-02-09T03:11:08.172212529Z"
      tree: "60e681491ac50334c57de185e45e29fe6b66faee0872d87e37daa22d606b7521"
      paths:
        -  "/example-com-master-solr-prebackuppod.solr.tar"
      hostname: "example-com-master-solr-prebackuppod"
      username: ""
      uid: 0
      gid: 0
      tags: null
    - id: "4038fcde41b31169dbd74c8923c92356e14a9dbff5b1247b825d656cffacfdc1"
      time: "2020-02-09T03:11:08.172212529Z"
      tree: "5136413b575b6cc078b3d83791143d6c7de5adbbdd474d61b146f5d1d872e369"
      paths:
        -  "/example-com-master-mariadb.mariadb.sql"
      hostname: "example-com-master-mariadb"
      username: ""
      uid: 0
      gid: 0
      tags: null
```

When a prune operation occurs, remove any pruned snapshots from this resource.

For Lagoon, we could then watch for changes to this resource to update the displayed backups for a specific namespace inside of Lagoon. This would reduce our need for the webhook payload being sent, and it would mean we don't need to process so much data from the webhook payload.

Another option would be to have an individual resource called `Snapshot` which could be like this
```
spec:
  bucketName: "example-bucket"
  id: "cb75d45c263487bda966eea844414edaab1a353c2a0996289cbf13572e22c61f"
  time: "2020-02-09T03:11:08.172212529Z"
  tree: "60e681491ac50334c57de185e45e29fe6b66faee0872d87e37daa22d606b7521"
  paths:
     -  "/example-com-master-solr-prebackuppod.solr.tar"
  hostname: "example-com-master-solr-prebackuppod"
  username: ""
  uid: 0
  gid: 0
  tags: null
```

Then any time a snapshot is completed, just create a single resource in the namespace for where the snapshot was taken.
Pruning would be simply removing the `Snapshot` object.
We'd be able to watch for the deletion of these objects so we could update Lagoon with the available snapshots then.

Either way, removing the need for posting the sometimes gigantic webhooks for particular namespaces would be ideal.
