### ISSUE TITLE
[Bug] Updating schedule in Schedule spec does not update internal scheduler

### ISSUE THREAD

**Issue by ccremer** [vshn/k8up#237]
## Describe the bug

Changed the schedule in a Schedule CR does not update the schedule in 

## Additional context

A restart of K8up is likely going to fix the problem, since the internal scheduler will be rebuilt from the Spec

## Logs

If applicable, add logs to help explain your problem.
```console
2020-12-23T15:27:50.772+0100	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "backup.appuio.ch", "reconcilerKind": "Schedule", "controller": "schedule", "name": "k8up-lagoon-backup-schedule", "namespace": "drupal-example-test1-dev"}
```

## Expected behavior

K8up should replace the internal schedule to the new spec

## To Reproduce

1. Create schedule spec
```yaml
spec:
  backup:
    schedule: '*/30 * * * *' # something bigger than 10min
```
1. Change schedule spec
```yaml
spec:
  backup:
    schedule: '* * * * *'
```
2. waited for 10 minutes and still nothing
also no backup object was created:
```
❯ k get backups
No resources found in drupal-example-test1-dev namespace.
```

## Environment (please complete the following information):

- Image Version: e.g. v1.0.0-rc1
- K8s Version: v1.18
- K8s Distribution: Rancher
