### ISSUE TITLE
Implement HA for the operator

### ISSUE THREAD

**Issue by Kidswiss** [vshn/k8up#244]
## Summary

**As** K8s cluster admin
**I want** to do maintenance on the cluster
**So that** no backup schedules are missed

## Context

Currently the operator doesn't support running in HA. So if a cluster node evicts the operator due to maintenance it could happen, that it misses one or multiple schedules until it's started again.

## Out of Scope

* Pod affinity etc. configuration for the deployment should be handled in the [Helm chart](https://github.com/appuio/charts/tree/master/k8up). Although a simple example should be shipped with the repository.

## Acceptance criteria

*Given* a schedule
*When* operator is evicted from one node
*Then* the backup instance will trigger schedules

## Implementation Ideas

* The operator SDK also provides some stubs for the HA stuff like leader election. We'll need to research a bit how this works and what consequences this would have.

**Comment by ccremer** [comment]
Just played with leader election in e2e test env.

Basically, the leader election is like a mutex: Only 1 pod can be leader.
When the 2nd Pod starts up with leader election enabled, it searches for a specific config map that holds some leader information. Every 15s the waiting Pods will query whether the leader pod is still available:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: d2ab61da.syn.tools
  namespace: k8up-system
  annotations:
    control-plane.alpha.kubernetes.io/leader: >-
      {"holderIdentity":"k8up-operator-57ddc459dd-kjqf8_5e009683-f123-4a5d-8f91-e62de130500f","leaseDurationSeconds":15,"acquireTime":"2020-12-28T16:50:55Z","renewTime":"2020-12-28T16:52:38Z","leaderTransitions":12}
```

There is no particular order. That being said, with timing it could happen that after the 1st pod is deleted, a 3rd gets spawned and immediately gets the leader.

When K8up starts up as "backup", this is the log:
```console
2020-12-28T16:50:41.214Z	INFO	setup	Starting K8up operator	{"version": "", "date": "", "commit": ""}I1228 16:50:41.223821       1 leaderelection.go:242] attempting to acquire leader lease  k8up-system/d2ab61da.syn.tools...2020-12-28T16:50:41.224Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
```
It's waiting until it gets the leaders, after that it will start the controllers. Meaning there is no querying for CRs or building the internal cron scheduler. In other words, it reduces "startup time" to 15s, but there is no "Sync" of data between the pods.

Do we really have a use-case where we need to sync the in-memory state of K8up? This gets complicated real quick.
