### ISSUE TITLE
Merged resources are stored in the wrong CR object

### ISSUE THREAD

**Issue by ccremer** [vshn/k8up#276]
## Describe the bug

With #175 we have added a feature that allows setting default resources. However, the resources that are merged with the template from the Schedule object and also specified in the job spec end up being stored in the Schedule CR, instead of being updated in the job CR.

this will remove the possibility to alter global default resources for cluster admins after the first reconciliation.

## Additional context

See discussion here #260 

## Logs

The schedule gets updated with the following spec after reconcile:
```yaml
apiVersion: backup.appuio.ch/v1alpha1
kind: Schedule
metadata:
  name: schedule-test
  namespace: default
spec:
...
  prune:
    resources:
      requests:
        cpu: 250m
    retention:
      keepDaily: 14
      keepLast: 5
    schedule: '*/1 * * * *'
  resourceRequirementsTemplate:
    requests:
      cpu: 250m
```
and prune:
```yaml
apiVersion: backup.appuio.ch/v1alpha1
kind: Prune
metadata:
  name: prunejob-1609946760
  namespace: default
spec:
  resources:
    requests:
      cpu: 250m
```

## Expected behavior

* `.spec.prune.resources` should be empty in `Schedule`, also the `.spec.resourceRequirementsTemplate` should not be touched

## To Reproduce

1. Schedule Specs
```yaml
---
apiVersion: backup.appuio.ch/v1alpha1
kind: Schedule
metadata:
  name: schedule-test
spec:
  resourceRequirementsTemplate:
    requests:
      cpu: "250m"
  prune:
    schedule: '*/1 * * * *'
```
2. Set global default memory limit
```bash
kubectl set env deployment/k8up-operator BACKUP_GLOBALMEMORY_LIMIT=76M
```

## Environment (please complete the following information):

- Image Version: v1.0.0-rc2
- K8s Version: v1.18
- K8s Distribution: KIND

**Comment by cimnine** [comment]
Preventing the modification of the Schedule resource during reconciliation was already implemented in #260.

**Comment by ccremer** [comment]
I was just able to verify, based on this PR branch, that the schedule gets the memory from the global:
```
spec:
  backend:
    repoPasswordSecretRef:
      key: password
      name: backup-repo
    s3:
      accessKeyIDSecretRef:
        key: username
        name: backup-credentials
      bucket: k8up
      endpoint: 'http://10.144.1.224:9000'
      secretAccessKeySecretRef:
        key: password
        name: backup-credentials
  prune:
    resources:
      limits:
        cpu: 10m
    retention:
      keepDaily: 14
      keepLast: 5
    schedule: '*/1 * * * *'
  resourceRequirementsTemplate:
    requests:
      cpu: 250m
      memory: 76M
```

**Comment by ccremer** [comment]
ok, restart from clean:
```
make clean e2e-test
kubectl -n k8up-system set env deployment/k8up-operator BACKUP_GLOBALMEMORY_LIMIT=76M
k apply -f <the following file>
```
with this schedule:
```yaml
---
apiVersion: backup.appuio.ch/v1alpha1
kind: Schedule
metadata:
  name: schedule-test
spec:
  resourceRequirementsTemplate:
    requests:
      cpu: "250m"
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
      endpoint: http://10.144.1.224:9000
      bucket: k8up
      accessKeyIDSecretRef:
        name: backup-credentials
        key: username
      secretAccessKeySecretRef:
        name: backup-credentials
        key: password
  prune:
    schedule: '*/1 * * * *'
    retention:
      keepLast: 5
      keepDaily: 14
    resources:
      limits:
        cpu: "500m"
        memory: 128M
```
I get the following properties in prune object:
```yaml
spec:
  backend:
    repoPasswordSecretRef:
      key: password
      name: backup-repo
    s3:
      accessKeyIDSecretRef:
        key: username
        name: backup-credentials
      bucket: k8up
      endpoint: 'http://10.144.1.224:9000'
      secretAccessKeySecretRef:
        key: password
        name: backup-credentials
  resources:
    limits:
      cpu: 500m
      memory: 128M
    requests:
      cpu: 250m
      memory: 76M
```
The 76M should not appear at all if set via env var. The current commit doesn't fully resolve the bug. And somehow the Schedule object still gets it assigned in the resource Requirements template
