### ISSUE TITLE
Viewer and Editor roles are disabled

### ISSUE THREAD

**Issue by ccremer** [vshn/k8up#284]
## Describe the bug

Previous 0.x versions of K8up (helm chart) come with Viewer and Editor roles included.
This is not the case anymore.

## Additional context

* The Viewer and Editor roles are [already there, but not activated in Kustomize](https://github.com/vshn/k8up/tree/master/config/rbac)
* Old versions defined a catch-all ClusterRole like:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: k8up
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: k8up
    app.kubernetes.io/version: v0.1.10
    argocd.argoproj.io/instance: backup-k8up
    helm.sh/chart: k8up-0.6.1
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: k8up-edit
rules:
- apiGroups:
  - backup.appuio.ch
  resources:
  - '*'
  verbs:
  - '*'
```
* Since Helm charts is basing its RBAC objects on Kustomize, the newest Chart PR doesn't include viewer and editor roles either at this time.

## Expected behavior

Viewer and Editor roles should be included again.
However, we could discuss following options:

1. Use the fine-granular roles (for each CRD `archive`, `backup`, `check`. `restore`. `prune`, `schedule` `prebackuppod` its own viewer/editor role)
2. Use the catch-all roles mentioned like before
3. Combine both options 1) and 2) to support easy, but also granular role bindings
4. Split into "user-facing" and "system" roles, e.g. user facing are `schedule`, `prebackuppod` and `restore`(in one role definition), the rest is "system" (also in 1 role definition).
5. [ClusterRole aggregation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles)

## To Reproduce

1. Specs
```bash
kustomize build config/rbac
```
