### ISSUE TITLE
Memory full: Reconciling Backups every 30s causes OOM kill of operator

### ISSUE THREAD

**Issue by ccremer** [vshn/k8up#331]
## Describe the bug

When using PreBackups, they may get stuck waiting for a prebackup until succeed. However, there is a hardcoded 30s reconcile interval on the Backup controller, which starts to watch for prebackup in a separate goroutine. If they're stuck for whatever reason, they consume memory until being killed by a limit.

## Additional context

It takes about 20m until K8s restarts the 256 MB-limited container. Then, every (pre)backup gets reconciled again, waiting for prebackup, and the whole story begins anew.

When the memory is full, liveness probe to /metrics fails and the container is being restarted.

## Logs

If applicable, add logs to help explain your problem.
```console
k -n syn-backup top pods --containers
POD                     NAME            CPU(cores)   MEMORY(bytes)   
k8up-787c6855c5-q8rrj   k8up-operator   4m           211Mi
```
Staggering, ever increasing amount of goroutinges in the Prometheus metrics:
```
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 3651
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.15.6"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 1.62932488e+08
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 8.12564584e+08
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.659263e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 6.710431e+06
```

## Expected behavior

Reconciling every 30s should not be necessary if the jobs are already being watched.
Or alternatively, don't start to watch again.

## To Reproduce

Let operator run on the test cluster in syn-backup namespace.

## Environment (please complete the following information):

- Image Version: v1.0.0-rc5
- K8s Version: v1.18
- K8s Distribution: Rancher

**Comment by Kidswiss** [comment]
There's #137 about the asynchronous handling of the prebackup pods.

Do you have a better idea how we could make the operator wait for the creation without using go routines?

**Comment by ccremer** [comment]
Hm, this came spontaneously to my mind:
- We launch a job with the same image as the operator itself, but as a "client" with a reference to the job. e.g. `k8up prebackup --backup backup-job-asdf`. The client starts the actual PrebackupPod and waits for it, no go routine necessary.
- Once done, the client can update the backup job conditions, or directly launch wrestic itself.
- That way, we completely offload the waiting from the operator, and it helps going the "K8up as CLI" way

**Comment by ccremer** [comment]
But as a quick fix, what are the reasons to simply remove the hardcoded 30s interval and rely on watch updates?

**Comment by Kidswiss** [comment]
The 30 seconds retry is for the case where a job gets thrown out of the queue because there's an exclusive job running. The interval ensures that the job will be looked at again.

**Comment by Kidswiss** [comment]
Maybe we should try to figure out why they may get stuck in this state in the first place? While it's a quite ugly method it has been working reliably in k8up legacy for the past few years.

**Comment by ccremer** [comment]
After further investigation I think it may be related to the upgrade. Once I have completely deleted all `Backup` resources in a namespace, backups with prebackup started to work again. There are now 3 successful backups in syn-backup-cluster-objects.

we might update the documentation in #332 so that users need to delete scheduled backups before installing the new version

**Comment by Kidswiss** [comment]
Maybe the operator trips over the changes in the status subresource somewhere?

But the workaround is fine by me.

**Comment by ccremer** [comment]
That may also be a reason. the current backup objects were made with conditions introduced in rc3, but the conditions didn't provide the `message` and `reason` properties, which are required values. That means, I can't even edit the backup resources to add bogus reasons or even remove all conditions, because K8s always complained.

Furthermore, It might not be necessary to delete all backup objects, but just the prebackup deployment. After deleting the deployment resource, the next reconcile was able to start and succeed a prebackup. I would have to verify if subsequent backups still work.

However, some cleanup kind of fails with a `foregroundDeletion` finalizer:
```yaml
kind: Backup
apiVersion: backup.appuio.ch/v1alpha1
metadata:
  creationTimestamp: '2021-01-24T23:55:00Z'
  deletionGracePeriodSeconds: 0
  deletionTimestamp: '2021-01-25T23:55:34Z'
  finalizers:
    - foregroundDeletion
  generation: 2
  name: backupjob-1611532500
spec:
   ...
status:
  conditions:
    - lastTransitionTime: '2021-01-24T23:55:29Z'
      status: 'True'
      type: CleanupSucceeded
    - lastTransitionTime: '2021-01-24T23:55:00Z'
      status: 'True'
      type: PreBackupPodsAvailable
    - lastTransitionTime: '2021-01-24T23:55:07Z'
      status: 'True'
      type: PreBackupPodsReady
    - lastTransitionTime: '2021-01-24T23:55:29Z'
      status: 'True'
      type: PreBackupPodsRemoved
    - lastTransitionTime: '2021-01-24T23:55:00Z'
      status: 'True'
      type: RoleBindingReady
    - lastTransitionTime: '2021-01-24T23:55:00Z'
      status: 'True'
      type: RoleReady
    - lastTransitionTime: '2021-01-24T23:55:00Z'
      status: 'True'
      type: ServiceAccountReady
  started: true
```
Notes:
* this object uses rc3-style conditions with missing properties
* There is only one such backup left, other were able to be cleaned up
* There's this finalizer. I don't think K8up adds those

Only way to resolve that is by force deleting it, editing doesn't work: `k delete --force backup backupjob...`
