### ISSUE TITLE
OpenShift 3.11 missing RBAC for jobs/finalizers

### ISSUE THREAD

**Issue by Kidswiss** [vshn/k8up#379]
## Describe the bug

When deploying to OpenShift 3.11 we found that the operator can't create the jobs. We found following errors on the backup objects:
```
status:
    conditions:
    - lastTransitionTime: "2021-02-22T20:24:30Z"
      message: The resource is ready
      reason: Succeeded
      status: "True"
      type: PreBackupPodsReady
    - lastTransitionTime: "2021-02-22T20:24:07Z"
      message: 'unable to create  ''namespace/backup-schedule-backup-mmnr4'':
        jobs.batch "backup-schedule-backup-mmnr4" is forbidden: cannot set blockOwnerDeletion
        if an ownerReference refers to a resource you can''t set finalizers on: no
        RBAC policy matched, <nil>'
      reason: CreationFailed
      status: "False"
      type: Ready
```

It seems that the operator can't update finalizers on job objects. We adjusted the RBAC as follows (https://github.com/vshn/k8up/blob/master/config/rbac/role.yaml):
```
- apiGroups:
  - batch
  resources:
  - jobs
  - jobs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```

Which seemed to help.

Found some more instances where the permissions are needed: for backup `backup` objects. I'd suggest to go through the code and add the finalizer permissions accordingly for object where we use it.

## Additional context

Seems only to happen on 3.11 as we have other deployments on k8s that don't suffer this issue.

## Expected behavior

K8up can create jobs on OpenShift 3.11 without issues.

## To Reproduce

1. Install k8up via helmfile on OpenShift 3.11
2. Run a backup
3. The job won't be created and k8up will retry every 30 seconds (as expected)

## Environment (please complete the following information):

- Image Version: v1.0
- K8s Version: 1.11
- K8s Distribution: OpenShift 3.11
