### ISSUE TITLE
v1.0.3. backup broken

### ISSUE THREAD

**Issue by gi8lino** [vshn/k8up#395]
## Describe the bug

if a backup takes longer as some seconds, it get an error. With v1.0.2. everything works fine.

## Logs

```console
I0312 12:32:36.453781       1 logging.go:180] wrestic/backup/progress "level"=0 "msg"="progress of backup"  "percentage"="0.00%"
I0312 12:32:36.454783       1 logging.go:180] wrestic/backup/progress "level"=0 "msg"="progress of backup"  "percentage"="0.00%"
E0312 12:32:36.455783       1 logging.go:156] wrestic/backup/progress "msg"="can't decode restic json output" "error"="invalid character 'L' looking for beginning of value"  "string"="Load(\u003cdata/4193b3e209\u003e, 0, 0) returned error, retrying after 391.517075ms: Access Denied."
E0312 12:32:36.458755       1 main.go:185] wrestic "msg"="backup job failed" "error"="cmd.Wait() err: -1"  ```
```

## Environment

- Image Version: e.g. v1.0.3
- k3s version v1.20.4+k3s1 (838a906a)
- go version go1.15.8

**Comment by Kidswiss** [comment]
Hi @gi8lino 

The error `Load(\u003cdata/4193b3e209\u003e, 0, 0) returned error, retrying after 391.517075ms: Access Denied.` indicates that restic can't access the backup bucket.

Does the exact same backup work with 1.0.2?

**Comment by gi8lino** [comment]
Hi @Kidswiss 

Yes, with v1.0.2 everything worked fine!

**Comment by Kidswiss** [comment]
Can you try to run the backup with another wrestic version? e.g. 0.1.9 or 0.2.0 and see if it still happens?

**Comment by gi8lino** [comment]
I tried it with wrestic v0.2.0 and got the same error:

```console
I0312 13:11:15.721907       1 utils.go:81] wrestic/backup/progress "level"=0 "msg"="progress of backup"  "percentage"="0.00%"
E0312 13:11:15.723861       1 utils.go:69] wrestic/backup/progress "msg"="can't decode restic json output" "error"="invalid character 'L' looking for beginning of value"  "string"="Load(\u003cdata/4193b3e209\u003e, 0, 0) returned error, retrying after 391.517075ms: Copy: Access Denied."
E0312 13:11:15.739853       1 main.go:182] wrestic "msg"="backup job failed" "error"="cmd.Wait() err: signal: broken pipe"
```

**Comment by cimnine** [comment]
@gi8lino

Can you share a Backup definition which triggers this behaviour on your side?
With that I would like to learn whether the Backup just takes a long time because it is big in size, or it because a `BackupCommand` is taking a long time, or what the reason is, so that I can model this locally.

**Comment by cimnine** [comment]
I think this has nothing to do with how long the command runs.

```yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: annotated-subject-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subject
  template:
    metadata:
      labels:
        app: subject
      annotations:
        k8up.syn.tools/backup: 'true'
        k8up.syn.tools/backupcommand: 'echo Hello' # This command runs almost instantly
        k8up.syn.tools/file-extension: '.txt'
    spec:
      containers:
      - name: subject-container
        image: quay.io/prometheus/busybox:latest
        imagePullPolicy: IfNotPresent
        args:
        - sh
        - -c
        - |
          printf '$BACKUP_FILE_CONTENT' | tee '/data/$BACKUP_FILE_NAME' && \
          ls -la /data && \
          echo "test file '/data/$BACKUP_FILE_NAME' written, sleeping now" && \
          sleep infinity
        securityContext:
          runAsUser: $ID
        volumeMounts:
        - name: volume
          mountPath: /data
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: subject-pvc
```

This simple deployment (based on our E2E-tests) fails with the same error.

**Comment by Kidswiss** [comment]
@cimnine Your example uses a prebackup command, does it also fail for backups from PVCs?

**Comment by gi8lino** [comment]
@cimnine 
do you mean this:

```yaml
apiVersion: backup.appuio.ch/v1alpha1
kind: Backup
metadata:
  name: test-backup-7r8bx
  namespace: test
spec:
  backend:
    s3:
      bucket: test
```

I think the backup size doesn't matter. The error occurs even it the pvc is only 4.0K

**Comment by cimnine** [comment]
@gi8lino Do make use of `PreBackupPod`s or the `k8up.syn.tools/backupcommand` annotation on Pods?

**Comment by gi8lino** [comment]
@cimnine 

The `PreBackupPods` I use only for the cluster-backup (single node k3s).
For SQL'ish stuff I use the annotation `k8up.syn.tools/backupcommand` on the deployment.
For PVC's (all are RWO) I set the annotation `k8up.syn.tools/backup: "true"`.

**Comment by cimnine** [comment]
@gi8lino so far I was not able to replicate the exact same issue. I've found another problem (https://github.com/vshn/wrestic/issues/78), but that isn't actually the same problem.

Would you mind doing two things for me?

- First, can you tell me what kind of S3 implementation you are using? I.e. is it minio, ceph, AWS? And – if it's self-hosted – what version you're using?
- Second, could you try running K8up `1.0.3` with wrestic `0.1.9`?
  The reason I'm asking is that in version 0.2.x of wrestic, the underlying _restic_ binary was updated, and as far as I understood it contains quite some changes to the S3-related code. Therefore I would like to rule out that this triggers some kind of incompatibility with your S3.

**Comment by gi8lino** [comment]
@cimnine

I have minio installed thru helm:
chart version: `8.0.10`
VERSION: `2021-02-14T04:01:33Z`
PLATFORM: `Host: minio-74557b8485-s7x7v | OS: linux | Arch: amd64`
RUNTIME: `Version: go1.15.7 | CPUs: 4`

with k8up `1.0.3` and wrestic `0.1.9` k8up it works fine.

It's a self-hosted single node k3s server.

**Comment by schemen** [comment]
Hi!

I wanted to report the same error on my infrastructure.

Minio, simple docker install: `2021-03-12T00:00:47Z` on a baremetal host with the storage attached via NFS.
k8up is version `k8up-1.0.3` installed via helm, on a K3s  3 node cluster.

**Comment by schemen** [comment]
I have updated my minio to the latest version `2021-03-17T02:33:02Z` and the backup resumed.

What I did not check:
* I didn't check the logs on the minio server side
* I didn't restart minio to see if this might've been the cause. Maybe @gi8lino you can check?

What also seemed weird to me that it was about half of the namespaces that were failing. The other half was doing just fine continuing the backups on schedule.

**Comment by gi8lino** [comment]
@cimnine 

I restarted the minio deployment and tried to do some backups.

One PVC (~17MB) worked fine.
For the other PVC (1.3 GB, 3.6 GB & 356 GB) I get this kind of errors:

```console
I0325 10:42:11.373640       1 logging.go:180] wrestic/backup/progress "level"=0 "msg"="progress of backup"  "percentage"="35.26%"
E0325 10:42:11.373800       1 logging.go:156] wrestic/backup/progress "msg"="can't decode restic json output" "error"="unexpected end of JSON input"  "string"="{\"message_type\":\"status\",\"percent_done\":0.355037"
E0325 10:42:11.375847       1 main.go:185] wrestic "msg"="backup job failed" "error"="cmd.Wait() err: -1"  
```

**Comment by schemen** [comment]
@gi8lino I get this error from time to time, it seems to be able to recover though after a few attempts.

**Comment by cimnine** [comment]
I've created an issue in https://github.com/vshn/wrestic/issues/79 for the percentage problem.

While doing so, I've found the wrestic issue https://github.com/vshn/wrestic/issues/76. This seems to describe the same issue as @gi8lino reports, doesn't it?

**Comment by Kidswiss** [comment]
I'd suggest to collect output parsing issues in vshn/wrestic#79. We should also not abort a backup on a single output line that can't be parsed.

I don't think it's related to  vshn/wrestic#76 though. Because restic won't exit in those cases. But here it returns as indicated by:
```
E0325 10:42:11.375847       1 main.go:185] wrestic "msg"="backup job failed" "error"="cmd.Wait() err: -1"
```

**Comment by cimnine** [comment]
We decided that we first want to improve the part in wrestic that parses the log messages from `restic`. Because currently we're not sure whether the backup fails because the parsing of the output failes, or whether the underlying restic failed because of some reason.

**Comment by Kidswiss** [comment]
I tested a bit how Minio behaves.

First I uploaded something to a local Minio instance and then removed the permissions of the file:
```
10:53:02 in baas/minio/test
➜ ll
total 664
drwxr-xr-x  3 simonbeck  staff      96 Mar 30 10:52 .
drwxr-xr-x@ 5 simonbeck  staff     160 Mar 30 10:52 ..
----------  1 simonbeck  staff  338373 Mar 30 10:52 Clipboard - March 29, 2021 1_18 PM.png
```

Then I tried to download the file, minio showed these errors in the log:
```
API: SYSTEM()
Time: 10:53:12 CEST 03/30/2021
DeploymentID: 0366f684-76ec-4f28-8a40-aa47d38e5a69
Error: Prefix access is denied: test/Clipboard - March 29, 2021 1_18 PM.png (cmd.PrefixAccessDenied)
       3: cmd/web-handlers.go:2442:cmd.toWebAPIError()
       2: cmd/web-handlers.go:2452:cmd.writeWebErrorResponse()
       1: cmd/web-handlers.go:1471:cmd.(*webAPIHandlers).Download()
```

Also it returned an access denied to my browser:
![image](https://user-images.githubusercontent.com/7460550/112966282-5f745900-914a-11eb-8e97-cbbd71908cbb.png)

So this is not necessarily an issue of wrestic/restic itself but could indicate something wrong with the running Minio instance.

**Comment by gi8lino** [comment]
fyi

I updated k8up with helm to v1.0.4. Now it works:

```console
I0330 23:00:42.314151       1 backup.go:54] wrestic/backup "level"=0 "msg"="starting backup for folder"  "foldername"="test-data"
I0330 23:00:42.314175       1 command.go:82] wrestic/backup/command "level"=0 "msg"="Defining RESTIC_PROGRESS_FPS"  "frequency"=0.016666666666666666
I0330 23:00:44.546191       1 logging.go:168] wrestic/backup/progress "level"=0 "msg"="progress of backup"  "percentage"="0.00%"
I0330 23:00:45.636605       1 logging.go:160] wrestic/backup/progress "level"=0 "msg"="backup finished"  "changed files"=9 "errors"=0 "new files"=0
I0330 23:00:45.636744       1 logging.go:161] wrestic/backup/progress "level"=0 "msg"="stats"  "bytes added"=6922430 "bytes processed"=143459545 "time"=2.782663316
I0330 23:00:45.636909       1 handler.go:44] wrestic/statsHandler/promStats "level"=0 "msg"="sending prometheus stats"  "url"="http://prometheus-pushgateway.monitoring.svc.cluster.local:9091"
```

To test it I've created a backup of a PVC and a DB.

exemplary:

```yaml
kubectl apply -f - << EOF
apiVersion: backup.appuio.ch/v1alpha1
kind: Backup
metadata:
  name: manual-backup-2021-03-31-091709
  namespace: test
spec:
  backend:
    s3:
      bucket: test
EOF
```

I also tried to restore the DB-dump with the restic CLI. First, it didn't work, but after restarting minio it worked!
