### ISSUE TITLE
k8up doesn't cleanup PreBackup Pod when backup is finished

### ISSUE THREAD

**Issue by TheBigLee** [vshn/k8up#413]
## Describe the bug

we noticed a lot of prebackuppod running only with `sleep infinity` (so an increase of the cluster pod count up to 2492)

example of our current prebackup template

```yaml
spec:                                                                                                                                                                         
  backupCommand: /bin/sh -c "dump=$(mktemp) && mysqldump --max-allowed-packet=500M                                                                                            
    --events --routines --quick --add-locks --no-autocommit --single-transaction --no-create-db                                                                               
    --no-data -h $BACKUP_DB_HOST -u $BACKUP_DB_USERNAME -p$BACKUP_DB_PASSWORD $BACKUP_DB_DATABASE                                                                             
    > $dump && mysqldump --max-allowed-packet=500M --events --routines --quick --add-locks                                                                                    
    --no-autocommit --single-transaction --no-create-db --ignore-table=$BACKUP_DB_DATABASE.watchdog                                                                           
    --no-create-info -h $BACKUP_DB_HOST -u $BACKUP_DB_USERNAME -p$BACKUP_DB_PASSWORD                                                                                          
    $BACKUP_DB_DATABASE >> $dump && cat $dump && rm $dump"                                                                                                                    
  fileExtension: .mariadb.sql                                                                                                                                                 
  pod:                                                                                                                                                                        
    metadata:                                                                                                                                                                 
      labels:                                                                                                                                                                 
        app.kubernetes.io/instance: mariadb                                                                                                                                   
        app.kubernetes.io/managed-by: Helm                                                                                                                                    
        app.kubernetes.io/name: mariadb-dbaas
        helm.sh/chart: mariadb-dbaas-0.1.0
        <redacted>
        prebackuppod: mariadb
    spec:
      containers:
      - args:
        - sleep
        - infinity
        env:
```

we've created our template from https://k8up.io/k8up/1.0.0/how-tos/prebackuppod.html

```console
k top pod --sort-by=cpu -A | grep backup
namespaceW                              mariadb-prebackuppod-5ddc7b9888-zbcf2                               0m           0Mi             
namespaceX                               mariadb-prebackuppod-7bc8c87df8-66fm4                               0m           0Mi             
namespaceY                               mariadb-prebackuppod-7bc8c87df8-qpssv                               0m           0Mi             
namespaceZ                               mariadb-prebackuppod-56f649749c-qss9t                               0m           0Mi
```

```console
namespaceFoo mariadb-prebackuppod-7bc8c87df8-t4td2 -- bash 
PID   USER     TIME  COMMAND
    1 10006000  0:00 sleep infinity
   19 10006000  0:00 bash
   26 10006000  0:00 ps aux
```
Are these pods be tracked in any way by k8up and removed once the backup is done?

## Expected behavior

Prebackup pods are terminated and cleaned up properly.

## Environment (please complete the following information):

- Image Version: v1.0.3
- K8s Distribution: OpenShift
