### ISSUE TITLE
Legacy-crd x-kubernetes-int-or-string can not be applied on OpenShift 3.11

### ISSUE THREAD

**Issue by megian** [vshn/k8up#445]
## Describe the bug

The CRD definition of `x-kubernetes-int-or-string: true` can not be applied on OpenShift 3.11. The apply itself does work, but ArgoCD endless tries to apply this attribute as well. It looks like that it got ignored during the apply.

```
spec:
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            resources:
              properties:
                limits:
                  additionalProperties:
                    x-kubernetes-int-or-string: true
```

## Logs

```console

# oc -n syn get app backup-k8up
NAME          SYNC STATUS   HEALTH STATUS
backup-k8up   OutOfSync     Healthy

# oc -n syn describe app backup-k8up
...
  Normal  OperationCompleted  7s    argocd-application-controller  Partial sync operation to b4d94898153e8e1eec249b03025f4b59f77525e0 succeeded
  Normal  OperationStarted    2s    argocd-application-controller  Initiated automated sync to 'b4d94898153e8e1eec249b03025f4b59f77525e0'
```

## Expected behavior

ArgoCD can fully apply the CRDs.

## To Reproduce

1. Specs
```yaml

```
2. Commands
```bash

```

## Environment (please complete the following information):

- Image Version: e.g. v1.1
- K8s Version: e.g. v1.11
- K8s Distribution: OpenShift
