### ISSUE TITLE
kustomization CRD for BaaS

### ISSUE THREAD

**Issue by BorntraegerMarc** [vshn/k8up#97]
The docs currently mention how to [setup a backup schedule](https://vshn.github.io/k8up/getting-started/) with restic.

We use [kustomize](https://github.com/kubernetes-sigs/kustomize) to manage our k8s deployments & overlays

Is there any intend to publish an open source kustomization [CRD](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/fields.md#crds) for `apiVersion: backup.appuio.ch/v1alpha1`? It would be especially useful when having multiple S3 buckets so that I could define a variable per OCP project with the correct bucket name in it.

Currently I need to overwrite the whole object in every project:
```
apiVersion: backup.appuio.ch/v1alpha1
kind: Schedule
metadata:
  name: backup-pods
spec:
  backend:
    s3:
      bucket: XXX # This is now for every OCP project different
```

This could be simplified (with the help of a CRD) to a single base config:
```
apiVersion: backup.appuio.ch/v1alpha1
kind: Schedule
metadata:
  name: backup-pods
spec:
  backend:
    s3:
      bucket: $(BUCKET_NAME)
```
